### ISSUE TITLE
Section to show events

### ISSUE THREAD

**Issue by VesperAkshay** [ChiragAgg5k/cal-buddy#1]
### Issue Description: Add Events Display Section to Calendar

**Objective:**  
Implement a new section within the calendar interface that displays all events created by users.

**Background:**  
Currently, users can create events in the calendar, but there is no dedicated section to view all the events they have created. This feature will enhance user experience by providing a centralized location to review and manage events.

**Requirements:**

1. **Section Layout:**
   - Create a new section labeled "My Events" on the calendar page.
   - This section should be easily accessible and visually distinct from other calendar functionalities.

2. **Event Display:**
   - List all events created by the user, including:
     - Event Title
     - Date and Time
     - Location (if applicable)
     - Description (if provided)
   - Each event entry should be clickable, allowing users to view details or edit the event.

3. **Sorting and Filtering:**
   - Implement sorting options (e.g., by date, title).
   - Provide filtering options (e.g., by upcoming events, past events).

4. **Responsive Design:**
   - Ensure the section is responsive and displays correctly on various devices (desktop, tablet, mobile).

**Comment by ChiragAgg5k** [comment]
looks good akshay. assigned it to you

**Comment by ChiragAgg5k** [comment]
if you need any help do let me know

**Comment by VesperAkshay** [comment]
Thank you

**Comment by ChiragAgg5k** [comment]
@VesperAkshay any progress?

**Comment by ChiragAgg5k** [comment]
@VesperAkshay you have been unassigned due to inactivity.

**Comment by wenayy** [comment]
assign me this i will complete it quickly

**Comment by ChiragAgg5k** [comment]
@wenayy u are assigned

**Comment by ChiragAgg5k** [comment]
@wenayy any progress?
