### ISSUE TITLE
Add Dark Mode using nextThemes

### ISSUE THREAD

**Issue by ChiragAgg5k** [ChiragAgg5k/cal-buddy#11]
The site uses shadcn for styling, which has incredibly easy support for adding dark mode. You can follow the this documentation - https://ui.shadcn.com/docs/dark-mode/next

After adding darkmode, do check -

1. All text or heading is clearly visible
2. Add a toggle for switching between light and dark mode (in the horizontal navbar)
3. The toggle is present in mobile navigation as well

Do attach screenshots of the changes. Good luck and do ask any doubts if any!

**Comment by Sathyan-B** [comment]
Could you please assign me? I have experience on this. Thanks.

**Comment by ChiragAgg5k** [comment]
@Sathyan-B you are assigned! do let me know if you have any doubts

**Comment by abhi9ab** [comment]
@ChiragAgg5k could you please assign me this issue?

**Comment by abhi9ab** [comment]
@ChiragAgg5k could you please assign me this issue?

**Comment by Sathyan-B** [comment]
> @Sathyan-B you are assigned! do let me know if you have any doubts

Hi @ChiragAgg5k, Facing few errors while running the code. Can you share the env file?

**Comment by ChiragAgg5k** [comment]
@Sathyan-B You need to add the environment variables mentioned here - https://github.com/ChiragAgg5k/cal-buddy/blob/master/.env.example

Hope that helps!

**Comment by Sathyan-B** [comment]
> @Sathyan-B You need to add the environment variables mentioned here - https://github.com/ChiragAgg5k/cal-buddy/blob/master/.env.example
> 
> Hope that helps!

Hi @ChiragAgg5k, I have created a PR. Please check. Add comments for any modifications. Thanks https://github.com/ChiragAgg5k/cal-buddy/pull/23

**Comment by ChiragAgg5k** [comment]
<img width="1277" alt="Screenshot 2024-10-11 at 3 23 12 PM" src="https://github.com/user-attachments/assets/abb4e10d-550e-483c-8494-bcf017019de4">

you need to create something similar to this

**Comment by Sathyan-B** [comment]
<img width="1723" alt="Screenshot 2024-10-13 at 9 32 47 AM" src="https://github.com/user-attachments/assets/0356e22c-ef3c-44fb-abad-34f0583bdfc1">
<img width="1723" alt="Screenshot 2024-10-13 at 9 32 57 AM" src="https://github.com/user-attachments/assets/491c6318-2e6a-42c6-a81d-347318489c29">
@ChiragAgg5k Please check now. Let me know your comments.
