### ISSUE TITLE
Modularize and cleanup Dashboard page

### ISSUE THREAD

**Issue by ChiragAgg5k** [ChiragAgg5k/cal-buddy#13]
As you can see in the dashboard page [here](https://github.com/ChiragAgg5k/cal-buddy/blob/master/src/app/dashboard/page.tsx), its a mess. all the code is inside this single file.

You need to cleanup the code and modularize it, breaking into the following components:

 Component Name | File Name
1. QuickActions - `quick-actions.tsx`
2. TasksComponent - `tasks.tsx`
3. RecentActivity - `recent-activity.tsx`

All the component files will be in the `/src/components/dashboard` folder only. Since these components will require shared states, such as recent activity will be required to be shared by other two components, you will have to be clever with the declaration of sharing of states. 

Its a bit challenging issue for someone new to react and next. So only opt for it if you think you can. Furthermore please dont hesitate to ask any doubts you might have

**Comment by abhi9ab** [comment]
@ChiragAgg5k, could you assign me to this issue? Thanks!

**Comment by ChiragAgg5k** [comment]
@abhi9ab you are assigned
