### ISSUE TITLE
Add animations to the landing page

### ISSUE THREAD

**Issue by ChiragAgg5k** [ChiragAgg5k/cal-buddy#14]
I recently updated the hero section of the landing page to include a grid background and some animations. I want you to keep this design and animation language consistent throughout the landing page. Specifically - 

1. In key features, add staggered reveal of the features, as well as some infinite animation on the icons.
2. In action, add typing animation to the chats.
3. Add some unique reveal to the pricing section
4. Similar for footer section

These are just some example animations. Final result is totally upto your creativity.

You are advised (but not restricted) to use these tools - 

1. https://www.framer.com/motion/
2. https://ui.aceternity.com/
3. https://magicui.design/
4. https://michalsnik.github.io/aos/

Make sure the design of the page stays consistent.

**This issue can be multi assigned** - the PR with the best results will end up getting merged!

**Comment by vizzv** [comment]
@ChiragAgg5k I like the product idea and start contributing to this.
So, can you please assign me.

**Comment by ChiragAgg5k** [comment]
@vizzv you are assigned! good luck

**Comment by abhi9ab** [comment]
Hi @ChiragAgg5k,

I have made some progress on this issue and would like to raise a pull request to show you the enhancement. Could you please assign this issue to me?

**Comment by ChiragAgg5k** [comment]
@abhi9ab sorry but it has just been 2 days since the last assignment. i will assign it to you once i feel its been left inactive

**Comment by vizzv** [comment]
Hii,@ChiragAgg5k 
I think I can not contribute as aspected .So ,please assign to @abhi9ab .

**Comment by ChiragAgg5k** [comment]
@abhi9ab would you still like to work on this issue?

**Comment by abhi9ab** [comment]
Sure

**Comment by abhi9ab** [comment]
I have a pull request ready for this issue. Could you assign this issue to me ?

**Comment by ChiragAgg5k** [comment]
@abhi9ab you are assigned! sorry for the delay i was really busy with exams. do raise the PR whenever you can
