### ISSUE TITLE
Add custom sign in page

### ISSUE THREAD

**Issue by ChiragAgg5k** [ChiragAgg5k/cal-buddy#15]
The project uses Clerk for authentication. Currently it just uses the default model based sign in UI. By following clerk documentation, you need to make a custom sign in page. 

The page will be made like at `/src/app/(auth)/signin/page.tsx`

Clerk has a wonderful guide on how to do so - https://clerk.com/docs/custom-flows/email-password-mfa#build-a-custom-sign-in-flow-with-multi-factor-authentication

For design you can take inspiration from shadcn example authentication - 

<img width="1221" alt="Screenshot 2024-10-08 at 8 48 23 AM" src="https://github.com/user-attachments/assets/9e144901-b369-43e2-b290-7629e3f63ce7">

**Comment by abhi9ab** [comment]
@ChiragAgg5k , could you assign me ?

**Comment by ChiragAgg5k** [comment]
@abhi9ab you are assigned!
