### ISSUE TITLE
Navbar Responsiveness for Mobile Devices - Missing Hamburger Icon and Alignment Issues

### ISSUE THREAD

**Issue by tanish0912** [ChiragAgg5k/cal-buddy#2]
### Navbar Responsiveness for Mobile Devices - Missing Hamburger Icon and Alignment Issues

**Description:**

The navigation bar on the Cal Buddy website is not responsive when viewed on mobile devices. The following issues have been observed:

1. There is no hamburger menu icon displayed on mobile, which would typically condense the navigation items into a collapsible menu.
2. The website name "Cal Buddy" is not aligned correctly, and the text appears on two lines instead of one, which negatively affects the layout.

**Expected Behavior:**

1. A hamburger icon should appear on smaller screen sizes (mobile and tablets), replacing the full navigation links.
2. The "Cal Buddy" text and the navigation items should be aligned on the same line to improve visual consistency across all devices.

**Screenshot:**
<img width="329" alt="Screenshot 2024-09-27 at 12 07 10 AM" src="https://github.com/user-attachments/assets/0ee2a633-c666-4290-ab83-0d3b5f23b06f">

**Comment by tanish0912** [comment]
@ChiragAgg5k I would like to work on this issue please assign it to me.

**Comment by ChiragAgg5k** [comment]
Tanish thanks for raising this issue. You have been assigned!

**Comment by tanish0912** [comment]
I have raised the pr, please check.
