### ISSUE TITLE
Integrate Google Calendar

### ISSUE THREAD

**Issue by ChiragAgg5k** [ChiragAgg5k/cal-buddy#25]
Fullcalendar, the library being used to render calendar on the website allows you to sync your events from google calendar. Its a simple addition, and the docs for it can be found here - https://fullcalendar.io/docs/google-calendar

Create a new environment variable called `NEXT_PUBLIC_GOOGLE_CALENDAR_API_KEY`.

Do thoroughly check if the integration is working as expected and attach proof in the PR.

Happy coding :D

**Comment by abhi9ab** [comment]
Could you assign me this issue ?

**Comment by ChiragAgg5k** [comment]
@abhi9ab you are assigned!
