### ISSUE TITLE
Made Footer Cleaner 

### ISSUE THREAD

**Issue by Indrajeety993648** [ChiragAgg5k/cal-buddy#3]
### Description:
The current footer design and functionality have the following issues:
- **"All rights reserved"** is not centered properly.
- **"Privacy"**, **"Terms"**, and **"Policies"** links are not well placed and lack visual appeal.
- Clicking on **"Terms of Service"** does not show any content or redirect properly.
- There is an issue with the positioning and functionality of the **social media links**.

### Expected Behavior:
- **"All rights reserved"** should be centered properly.
- **"Privacy"**, **"Terms"**, and **"Policies"** should have proper placement, better styling, and be functional.
- Clicking on the **Terms of Service** link should direct the user to the correct page or display the correct content.

### Actual Behavior:
- The "All rights reserved" text is not centered.
- The **Privacy**, **Terms**, and **Policies** links are not visually appealing or properly placed.
- The **Terms of Service** link does not show any content or redirect correctly.
- Social media links may not be working as expected.

### ScreenShot
![Screenshot from 2024-09-27 12-31-40](https://github.com/user-attachments/assets/089b8618-431c-47e9-abc5-c2462d80fd30)
reenshots:

**Comment by Indrajeety993648** [comment]
@ChiragAgg5k  I would like  to work on this issue , Please assign it to me

**Comment by ChiragAgg5k** [comment]
@Indrajeety993648 any progress?

**Comment by tanish0912** [comment]
If the work is not yet done, I am happy to contribute on this.
Please assign it to me.

**Comment by ChiragAgg5k** [comment]
@tanish0912 can you please briefly explain what additions/ modifications are you going to make?

**Comment by tanish0912** [comment]
What @Indrajeety993648 has mentioned above i will make those changes. Also will add the hover effect you mentioned.

**Comment by ChiragAgg5k** [comment]
You are assigned!

**Comment by tanish0912** [comment]
![1](https://github.com/user-attachments/assets/9c3d8784-5b38-47c4-a46d-b54a15ba659c)
![2](https://github.com/user-attachments/assets/e8745550-5b9c-422e-a7b9-eee140622f07)
![3](https://github.com/user-attachments/assets/b1c33c36-9307-42c3-bb5c-d436690e2520)

I have made footer cleaner. Also added the hover behaviour as requested and as their in the website at other areas.
I have tried keeping the footer as clean and minimal as possible.
@ChiragAgg5k Please let me know if we can proceed with this or there are any other changes which can be done.
Thanks.

**Comment by Indrajeety993648** [comment]
@ChiragAgg5k  It looks cleaner , this  PR   should be  merged

**Comment by tanish0912** [comment]
I have made the pr please check.

**Comment by tanish0912** [comment]
@ChiragAgg5k I have raised the pr
https://github.com/ChiragAgg5k/cal-buddy/pull/21
Please review.
