### ISSUE TITLE
Add Sonner from shadcn library

### ISSUE THREAD

**Issue by ChiragAgg5k** [ChiragAgg5k/cal-buddy#32]
I want to add `sonner` library via shadcn to add more feedbacks for the user and improve the overall user experience. For this PR i just want you to add the component and implement it for - 

1. When user clicks on any of the pricing options on the landing page, show title: `Its Free!`, description: `Cal Buddy is completely free to use... (for now) :D`
2. When user enters his/her email in the footer, show title: `Coming Soon`, description: `You can subscribe to the newsletter very soon in future`

Link to the component - https://ui.shadcn.com/docs/components/sonner

Do ask any doubts you have. Happy coding :D

**Comment by SartHak-0-Sach** [comment]
Hi @ChiragAgg5k, I would love to work on this issue, please assign me this and allow me to contribute to it

**Comment by ChiragAgg5k** [comment]
@SartHak-0-Sach you are assigned!

**Comment by SartHak-0-Sach** [comment]
Hi @ChiragAgg5k, I am facing a lot of issues in simply setting up the project

Few issues that I am facing are-
1) Conflicting dependencies
2) Unable to create any branches for my work
3) A few other minor issues that I am yet to figure out that are causing errors in config files

Did you face these too?

**Comment by ChiragAgg5k** [comment]
@SartHak-0-Sach you shouldnt be facing these issues... can you attach some screenshots so i can check whats really wrong on your side?

**Comment by SartHak-0-Sach** [comment]
Since I don't have the history of all issues I faced at the moment, but I know that the single root cause of all these issues was when I did npm install, and after facing error in that I did npm install --legacy-peer-deps after which I started facing all these issues

**Comment by SartHak-0-Sach** [comment]
Wait, nevermind its resolved now, here is my first pull-request with the sonner pricing task completed :)
