### ISSUE TITLE
Add more useCopilotActions and useCopilotChatSuggestions

### ISSUE THREAD

**Issue by ChiragAgg5k** [ChiragAgg5k/cal-buddy#5]
You can use useCopilotActions and useCopilotChatSuggestions to define various interactions with the calendar. Some interactions that are already defined include the suggestion "counting of today's events,"  which has a corresponding action that counts the number of events in the events state. Think of more creative actions and suggestions and implement them!

If facing any issues, feel free to ask.

**Comment by AnanteshG** [comment]
Hi! I'd love to work on this issue. Could you please assign it to me?

**Comment by ChiragAgg5k** [comment]
@AnanteshG you are assigned! Do checkout copilotkit's documentation:

1. https://docs.copilotkit.ai/copilot-suggestions
2. https://docs.copilotkit.ai/reference/hooks/useCopilotAction

If you any doubts feel free to ask!

**Comment by AnanteshG** [comment]
Should I remove these
![{B58A20BE-D131-4365-A99E-0298CB9F1137}](https://github.com/user-attachments/assets/18665c25-f9df-475b-8f86-fc31fc4c7f0a)
and add new ideas
OR
should I add them on top of these?

**Comment by ChiragAgg5k** [comment]
add new ones @AnanteshG
