### ISSUE TITLE
Adding localstorage support

### ISSUE THREAD

**Issue by ChiragAgg5k** [ChiragAgg5k/cal-buddy#9]
Currently the project is not connected to a database. This is a feature to be implement in future. For now store the values for the user's events in localstorage, specifically these two values:

- events -> inside the [/src/components/smart-calendar.tsx](https://github.com/ChiragAgg5k/cal-buddy/blob/master/src/components/smart-calendar.tsx) file
- tasks -> inside the [/src/app/dashboard/page.tsx](https://github.com/ChiragAgg5k/cal-buddy/blob/master/src/app/dashboard/page.tsx) file

Make sure to thoroughly test before creating a pull request. Name the feature branch as `localstorage-support`.

For any doubts, feel free to ask. Happy coding!

**Comment by genial-mani** [comment]
Could you please assign me I want to work on this?
I already worked on this before.

**Comment by ChiragAgg5k** [comment]
@genial-mani you are assigned! feel free to ask any doubts you might have

**Comment by ChiragAgg5k** [comment]
@genial-mani are you still working on this issue? its kind of an urgent one

**Comment by genial-mani** [comment]
yes

**Comment by abhi9ab** [comment]
I see this is an urgent issue and I'd like to help resolve it as soon as possible. Could you please assign this issue to me ?

**Comment by ChiragAgg5k** [comment]
Okay.. I am multi assigning this one. Who ever created the pr first will get it merged. @genial-mani
